name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        configuration: [ Debug, Release ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore /p:Configuration=${{ matrix.configuration }}

      - name: Build
        run: dotnet build --no-restore --configuration ${{ matrix.configuration }}

      - name: Test
        run: dotnet test --no-restore --no-build --configuration ${{ matrix.configuration }}
